### ISSUE TITLE
Make a Version of the Data

### ISSUE THREAD

**Issue by LinguList** [GClarte/SignLanguagesPhylogeny#2]
In GitHub, making versions is very easy, and it gives you the possibility to "freeze" the status of the repository, so those who wish to refer to it can make sure they refer to the version you used in the underlying paper. When reviewing your study just now, I mentioned this explicitly and also recommended to please archive this with Zenodo, to make sure you do not depend on the big publishing houses to take care of your data (they don't care).

**Comment by robinryder** [comment]
@LinguList Thanks for the useful feedback! We have already archived this in Dryad. Are you suggesting that Zenodo is substantially better, and that we should also archive this in Zenodo?

**Comment by robinryder** [comment]
@LinguList Thanks for the useful feedback! We have already archived this in Dryad. Are you suggesting that Zenodo is substantially better, and that we should also archive this in Zenodo?

**Comment by robinryder** [comment]
The GitHub version is now [available](https://github.com/GClarte/SignLanguagesPhylogeny/releases/tag/v1).
We have also archived all code and data on Dryad (doi:10.5061/dryad.bnzs7h4h1); the archive will be made public when the paper comes out.
